# Generated by Django 4.2.5 on 2023-11-05 08:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="seller",
            name="aadhar",
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="seller",
            name="gst",
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="seller",
            name="pan",
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="seller",
            name="voter",
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
