# Generated by Django 4.2.5 on 2023-11-05 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_seller_aadhar_seller_gst_seller_pan_seller_voter"),
        ("marketplace", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="seller",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="accounts.seller"
            ),
        ),
    ]
